//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardOfDirector
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string EducationalQualification { get; set; }
        public string Catagory { get; set; }
        public string Comment { get; set; }
    }
}
