//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Results = new HashSet<Result>();
            this.StudentClasses = new HashSet<StudentClass>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public System.DateTime DateOfBirthDateTime { get; set; }
        public string Hometown { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public string PasportNo { get; set; }
        public string FatherName { get; set; }
        public string FatherContactNo { get; set; }
        public string FatherOccupation { get; set; }
        public string MotherName { get; set; }
        public string MotherContactNo { get; set; }
        public string MotherOccupation { get; set; }
        public string ParentAddress { get; set; }
        public string GuardianName { get; set; }
        public string GaurdianContactNo { get; set; }
        public string Relationship { get; set; }
        public string GuardianAddress { get; set; }
        public string PhoneNo { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
        public string Email { get; set; }
        public string PermanentAddress { get; set; }
        public string PermanentPostOffice { get; set; }
        public string PermanentDistrict { get; set; }
        public string PermanentDivision { get; set; }
        public string PermanentCountry { get; set; }
        public string PresentAddress { get; set; }
        public string PresentPostOffice { get; set; }
        public string PresentDistrict { get; set; }
        public string PresentDivision { get; set; }
        public string PresentCountry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClass> StudentClasses { get; set; }
    }
}
